services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
      MYSQL_USER: serviceusers
      MYSQL_PASSWORD: Usersservice
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    build:
      context: ./services/users
    container_name: users-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/users/.env
    volumes:
      - ./services/users:/app
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
