apiVersion: v1
kind: Service
metadata:
  name: users-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
