version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  users-service:
    build:
      context: ./services/users
    container_name: users-service
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
